# Exported from Render on 2024-10-19T19:53:09Z
services:
- type: web
  name: TCG_PAGE
  runtime: python
  repo: https://github.com/BigBossSpektrum/YGO
  plan: free
  envVars:
  - key: python_version
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python manage.py runserver
version: "1"
