# Generated by Django 5.1.3 on 2024-11-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_yugioh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='confirmpassword',
            new_name='password2',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='name',
        ),
    ]
