# Generated by Django 5.1.3 on 2024-11-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_yugioh', '0003_rename_lastname_usuarios_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='password',
            new_name='password1',
        ),
    ]
