# Generated by Django 5.1 on 2025-01-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yugioh', '0003_remove_card_archetype_remove_card_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
