# Generated by Django 5.1 on 2025-01-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_yugioh', '0004_card_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='desc',
            new_name='description',
        ),
    ]
