# Generated by Django 5.1.3 on 2025-01-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yugioh', '0004_rename_password_usuarios_password1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
