# Generated by Django 5.1 on 2025-01-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yugioh', '0005_rename_desc_card_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='archetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
