# Generated by Django 5.1.3 on 2025-01-03 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yugioh', '0005_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='archetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=255)),
                ('set_rarity', models.CharField(max_length=100)),
                ('set_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to='api_yugioh.card')),
            ],
        ),
    ]
