# Generated by Django 5.1 on 2025-01-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yugioh', '0006_card_archetype_card_race_card_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='humanReadableCardType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
