# Generated by Django 5.1 on 2025-01-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yugioh', '0007_card_humanreadablecardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='atk',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='defense',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
